sudo: false
language: python
python:
  - '3.6'

env:
  - TEST=molo_lint
  - TEST=testapp_lint
  - TEST=build

jobs:
  include:
    # Include a separate job for the node tests
    - language: node_js
      node_js: '6' # LTS version
      env: []
      cache:
        directories: [client/node_modules]
      before_install:
        - cd client
      install:
        - travis_retry npm install
      script:
        - npm run ci

      # Clear unused build steps
      services: []
      after_success: []
    - stage: deploy
      env: []
      before_install: []
      install: []
      script: 'true'
      after_success: []
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: Praekelt
        password:
          secure: "qtRWMDuVhLpkcZwZQ2F9b0DJAo4Lt8X6LMttXx039jx23AyovRlaL7X157vNJnXsXC2PeZ791NDXiAI070RpNvr18m0pRZS4IRQT/LyT2pxoRTAcs9a/Ep4Vk28/sbOtAB9cG6hTOQ5G9Degboaayoy4OGskJG7xIxMTjID0na5wt3u0gOHseV4v81kabmEGSsPFslaarNorzlQDhOL4J9JdgIOE33muf78+a10GYDe9YPaIF7oDwlLvUMIhRNeEo2Z9CEVSQITIVoUAAcGhwQlDBqf036qfvB5qRs+EZREAARwZhYA/CcLr0rgCAVeeAHpg2jhaxrekrdjYevNc/X9oqf0BZVMsCVXIGKaXoNPJ6FrTzx2Bwdatj1paHIu3oZG6PS53PyJZAM1NY3J2cuhSWvDvJoGICR9W5JQ6ZOAHI6gw5jNDE1m4ok3OEq3Lb1Oa0hB9IgmctbpnMhZtdzX5cVxxgv398eSBfE4jG+mD7WyORQq5KCxjoGCAtWtth0XntezwCDodJBByJwfYYp8p6bb2ofwHiIInwevbjx6mM4YpOWM/p4gdz/+0uv7U/f3yZMr/tr45i66BXUcCD1va71pKt1P2hY/roT9W1GWhZENUuhv0GxVbTrwJPnGxvv4lyN8I8YKKS4OXlvu1mNeHDGC9mfvFdKc7b0btF8I="
        on:
          tags: true
          all_branches: true

services:
  - elasticsearch
  - redis-server
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script: ./travis.sh
after_success:
  - coveralls
