sudo: false
language: python
python:
  - '3.6'

env:
  - TEST=molo_lint
  - TEST=testapp_lint
  - TEST=build

jobs:
  include:
    # Include a separate job for the node tests
    - language: node_js
      node_js: '6' # LTS version
      env: []
      cache:
        directories: [client/node_modules]
      before_install:
        - cd client
      install:
        - travis_retry npm install
      script:
        - npm run ci

      # Clear unused build steps
      services: []
      after_success: []
    - stage: deploy
      env: []
      before_install: []
      install: []
      script: 'true'
      after_success: []
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: Praekelt
        password:
          secure: JI8dx9kVSBeQ8jrNnW3i1+VSyc23e1hpbcqZPXIX+nPU1tt4LeEezYzX1hPLiwifNebHjXglU+8K5x7UI2BsIfa1B654mBNWzuMkARTrEx6tjpFMr88bR49fNd9T74oVP6iRGMfhh2no2hlRXHDC7DYNk1W4DC4XVjCk42Hne7zoDhX8vKAJ/9myGas19j5tbNCKKNtHOp4TkogUMu/6Wgnwg5ShksBBQIUL3Pkfy8H41JVzATvcXhw+Ufso/0pn49ovF97I2jQI9gUoQ+R6G/utvdq5RKemw0ZeyR8aj68mWNRfaB5kYIyopkG/x5qgUcqMTfY5Ooby2hXpusqYlfUCSL5Y5kvb7RKpt3u9ky8tU4fSZ2UhZl8RGflb0InMPN+4W/8oWWcwk4Vg+j2nibCKx2+BuZqdaJJsfXze/Qtc9aGffIesra6s9+Qtp7uIaIqaizLrADi1jAPDGf2IiCf3q2/ckWA3QWFwOGWNfGm5mjYhXdlio8leMJY7g8yffH4D9tPTVV/mKOYBkWfshgNbr6N0LXmdov1GWKO4QAJX364eGbmGs/CfuvSzyYN3+0awCql4y8yrw56lqTZK6Kho034tUHgSwmM0/qyAFO061zoR1vH6d6s8rMQBNtdYLylawP9vSwxZIVcgp/D3Djll1Mx+1sy6jRwJOw45bRo=
        on:
          tags: true
          all_branches: true

services:
  - elasticsearch
  - redis-server
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script: ./travis.sh
after_success:
  - coveralls
