sudo: false
language: python

matrix:
  include:
    - python: '2.7'

    # Include a separate job for the node tests
    - language: node_js
      node_js: '6' # LTS version
      cache:
        directories: [client/node_modules]
      before_install:
        - cd client
      install:
        - travis_retry npm install
      script:
        - npm run ci

      # Clear unused build steps
      services: []
      deploy: []
      after_success: []

    # Docker dev image
    - sudo: required
      services: docker
      env:
        global:
          - REGISTRY_USER=praekeltorgdeploy
          - REGISTRY_PASS=todo
      install:
        - git clone -b dev-image https://github.com/praekeltfoundation/docker-molo-bootstrap.git docker
      before_script:
        - image="$(awk '$1 == "FROM" { print $2; exit }' docker/onbuild/Dockerfile)"
        - cache_from="${image}:develop-onbuild"
        - docker pull "$cache_from" || true
      script:
        - python setup.py bdist_wheel && cp -r dist docker
        - docker build --pull --cache-from "$cache_from" -t "$image" -f docker/dev.dockerfile docker
        - docker build --cache-from "$cache_from" -t "$image:onbuild" docker/onbuild
      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - pip install docker-ci-deploy==0.3.0
        - version="$(git rev-parse --short HEAD)"
      deploy:
        provider: script
        script: dcd -t develop -V "$version" -L "$image" && dcd -t develop-onbuild -V "$version" -L "$image:onbuild"
        on:
          branch: develop

      # Clear unused build steps
      cache:
      before_install: []
      after_success: []

services:
  - elasticsearch
  - redis-server
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8 molo
  - molo scaffold testapp
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: TrR3EF0bUSLZFjvfp62Jjjc+d0HTjXRR5BGoM7K1ON4buyyq3AGj8Fvc20d8CN/jcpqnibj+L3MNZnFkgEjsCy7GRav42QTVtQPj5Sorodp8qM7e329do6VAtO3iL6uoG258gYD0oqM0PZjlZurGZjksI7P/IsaZXeFh2I4NyS5Dy/m9f1zhzo5fS4H5oOpK8ohTPe3l9yRBXHteaAZYSrC8pc05U82iSaiWY4RbtJfxB2lPsxTJCh7nrjsyOu+jOubxuandve6YrKnCdpb2JQaPOeSBVpxHxhlf47MTTp5Q4DCO0DLA+kDoBZ1aEkM5gULQihjrKRtmbbXr0AmA+KEVdtZ9KySkmZB8W4lJfz+nyhxvKYEujNKoRYsxLBb5Nxxs/wuy/JTSJBQwdxDff8Yqz0o0N4xsMRy389o06QpE1ARqXpNE7+JSODyZT4ojTMVSmuU2CpwxDSR5L6ZA61nhDECoGe39HLgXiB/LTXgLxCt8O41u+gNQwGbE0iL22C1hPrkT5qWgP6YoMIK8PvpJAw2PVlxnaGZISljPQmV5txBSfi8h7u+wPnRJIVqgaWiM9mM27LhjZnMKPUqIspkMEvc0YoAJ6QYRPsATEUMlZIg+U+FCeSlALNd1cCzxiritPPNOYw9JG2PVACLtnmxhe1L9ILVg48t4loeHxUc=
  on:
    tags: true
    all_branches: true
