language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - flake8 molo
  - py.test --ds=project.settings --verbose --cov molo molo
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: PL0ixvBN9Q8jfGViDYeW5JLieOiEiY2PrZSi0yrrf1/vQLgbj0NfrSXxK/hTHts/mHivXbyEtN4vgkAn/U+tZj+uvTV6UnwfpbTfxmFafINMbZNtHbCzuhdIN5VXN0FIMyuFP+reePI53NIEqmL/ZKCemdJy2THmUHnddSBq1F4=
  on:
    tags: true
    all_branches: true
