sudo: false
language: python
python:
  - '2.7'
  - '3.6'

env:
  - TEST=molo_lint
  - TEST=testapp_lint
  - TEST=build

matrix:
  include:
    # Include a separate job for the node tests
    - language: node_js
      node_js: '6' # LTS version
      env: []
      cache:
        directories: [client/node_modules]
      before_install:
        - cd client
      install:
        - travis_retry npm install
      script:
        - npm run ci

      # Clear unused build steps
      services: []
      deploy: []
      after_success: []
  allow_failures:
    - python: '3.6'

services:
  - elasticsearch
  - redis-server
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script: ./travis.sh
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: TrR3EF0bUSLZFjvfp62Jjjc+d0HTjXRR5BGoM7K1ON4buyyq3AGj8Fvc20d8CN/jcpqnibj+L3MNZnFkgEjsCy7GRav42QTVtQPj5Sorodp8qM7e329do6VAtO3iL6uoG258gYD0oqM0PZjlZurGZjksI7P/IsaZXeFh2I4NyS5Dy/m9f1zhzo5fS4H5oOpK8ohTPe3l9yRBXHteaAZYSrC8pc05U82iSaiWY4RbtJfxB2lPsxTJCh7nrjsyOu+jOubxuandve6YrKnCdpb2JQaPOeSBVpxHxhlf47MTTp5Q4DCO0DLA+kDoBZ1aEkM5gULQihjrKRtmbbXr0AmA+KEVdtZ9KySkmZB8W4lJfz+nyhxvKYEujNKoRYsxLBb5Nxxs/wuy/JTSJBQwdxDff8Yqz0o0N4xsMRy389o06QpE1ARqXpNE7+JSODyZT4ojTMVSmuU2CpwxDSR5L6ZA61nhDECoGe39HLgXiB/LTXgLxCt8O41u+gNQwGbE0iL22C1hPrkT5qWgP6YoMIK8PvpJAw2PVlxnaGZISljPQmV5txBSfi8h7u+wPnRJIVqgaWiM9mM27LhjZnMKPUqIspkMEvc0YoAJ6QYRPsATEUMlZIg+U+FCeSlALNd1cCzxiritPPNOYw9JG2PVACLtnmxhe1L9ILVg48t4loeHxUc=
  on:
    tags: true
    all_branches: true
